"repository rule for generating unpacked sysroot repositories from a lockfile."

load(":lockfile.bzl", "lockfile")
load(":translate_dependency_set.bzl", "dependency_set_transitive_package_keys")
load(":util.bzl", "util")

_SYSROOT_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

filegroup(
    name = "sysroot",
    srcs = ["."],
    visibility = ["//visibility:public"],
)
"""

def _ensure_mergedusr_compat_symlinks(rctx, unpack_dir):
    compat_symlinks = {
        "bin": "usr/bin",
        "sbin": "usr/sbin",
        "lib": "usr/lib",
        "lib32": "usr/lib32",
        "lib64": "usr/lib64",
        "libx32": "usr/libx32",
    }

    for root, target in compat_symlinks.items():
        root_path = unpack_dir + "/" + root
        target_path = unpack_dir + "/" + target

        if rctx.path(root_path).exists:
            continue
        if not rctx.path(target_path).exists:
            continue

        rctx.symlink(target_path, root_path)

def _materialize_deb_data_into_root(rctx, deb_path, work_dir, unpack_dir, bsdtar = None):
    setup_sh = """set -o errexit -o nounset -o pipefail
pkg='{pkg}'
work='{work}'
root='{root}'

member=""
while IFS= read -r entry; do
    case "$entry" in
        data.tar|data.tar.*)
            member="$entry"
            break
        ;;
    esac
done < <(ar t "$pkg")

if [[ -z "$member" ]]; then
    echo "No data archive found in $pkg" >&2
    exit 1
fi

data_archive="$work/$member"
ar p "$pkg" "$member" > "$data_archive"
""".format(
        pkg = deb_path,
        work = work_dir,
        root = str(rctx.path(unpack_dir)),
    )

    if bsdtar != None:
        extract_sh = (
            'data_file="$data_archive"\n' +
            'layer="$work/content.tar.gz"\n\n' +
            util.mergedusr_rewrite_script(str(bsdtar), dollar = "$") + "\n\n" +
            "tar --extract --file \"$layer\" --directory \"$root\" --no-same-owner --no-same-permissions\n" +
            'rm -f "$layer"\n'
        )
    else:
        extract_sh = "tar --extract --file \"$data_archive\" --directory \"$root\" --no-same-owner --no-same-permissions\n"

    extraction = rctx.execute([
        "bash",
        "-c",
        setup_sh + extract_sh,
    ])
    if extraction.return_code != 0:
        fail("Failed extracting deb payload from {}:\n{}\n{}".format(deb_path, extraction.stdout, extraction.stderr))

def _unpack(rctx, packages, dependency_set, sources, mergedusr, architecture):
    if architecture not in dependency_set["sets"]:
        fail("architecture '{}' is not present in dependency set '{}'".format(architecture, rctx.attr.depset_name))

    bsdtar = None
    if mergedusr:
        if not rctx.attr.bsdtar:
            fail(
                "bsdtar is required for mergedusr unpacking but was not provided. " +
                "This is an internal error; please file a bug.",
            )
        bsdtar = rctx.path(rctx.attr.bsdtar)

    unpack_dir = "sysroot"
    work_dir = str(rctx.path(".unpack_work_%s" % architecture))
    make_work_dir = rctx.execute(["mkdir", "-p", work_dir, str(rctx.path(unpack_dir))])
    if make_work_dir.return_code != 0:
        fail("Failed creating unpack work dir {}".format(work_dir))

    package_keys = dependency_set_transitive_package_keys(packages, dependency_set, [architecture, "all"])
    for package_key in package_keys:
        package = packages[package_key]
        deb_path = "{}/{}.deb".format(work_dir, util.sanitize(package_key))

        rctx.download(
            output = deb_path,
            sha256 = package["sha256"],
            url = [
                uri + "/" + package["filename"]
                for uri in sources[package["suite"]]["uris"]
            ],
        )

        _materialize_deb_data_into_root(rctx, deb_path, work_dir, unpack_dir, bsdtar = bsdtar)

    if mergedusr:
        _ensure_mergedusr_compat_symlinks(rctx, unpack_dir)

    cleanup = rctx.execute(["rm", "-rf", work_dir])
    if cleanup.return_code != 0:
        fail("Failed cleaning unpack work dir {}".format(work_dir))

def _sysroot_repository_impl(rctx):
    lockf = lockfile.from_json(rctx, rctx.attr.lock_content)

    sources = lockf.sources()
    packages = lockf.packages()
    dependency_sets = lockf.dependency_sets()
    dependency_set = dependency_sets[rctx.attr.depset_name]

    _unpack(
        rctx,
        packages,
        dependency_set,
        sources,
        rctx.attr.mergedusr,
        rctx.attr.architecture,
    )

    rctx.file("sysroot/BUILD.bazel", _SYSROOT_BUILD_TMPL)

sysroot_repository = repository_rule(
    implementation = _sysroot_repository_impl,
    attrs = {
        "depset_name": attr.string(doc = "INTERNAL: DO NOT USE"),
        "lock_content": attr.string(doc = "INTERNAL: DO NOT USE"),
        "architecture": attr.string(doc = "INTERNAL: Architecture to unpack and expose as //sysroot:sysroot."),
        "mergedusr": attr.bool(default = False, doc = "INTERNAL: Whether unpacking should normalize merged-/usr paths."),
        "bsdtar": attr.label(allow_single_file = True, doc = "INTERNAL: bsdtar binary from bsd_tar_toolchains, required when mergedusr=True."),
    },
)

