"repository rule for generating unpacked sysroot repositories from a lockfile."

load(":lockfile.bzl", "lockfile")
load(":translate_dependency_set.bzl", "dependency_set_transitive_package_keys")
load(":util.bzl", "util")

_SYSROOT_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

filegroup(
    name = "sysroot",
    srcs = ["."],
    visibility = ["//visibility:public"],
)
"""

def _materialize_deb_data_into_root(rctx, deb_path, ar_dir, unpack_dir):
    """Unpacks the data.tar.* payload of a .deb archive into unpack_dir.

    This relies exclusively on Bazel's built-in support for extracting
    the `ar` container format used by .deb files, and the nested `tar.*`
    payload, via repository_ctx.extract().
    """

    # .deb files are `ar` archives containing debian-binary, control.tar.*
    # and data.tar.* members. Extracting unpacks those members as plain,
    # uncompressed files (the ".deb" extension is auto-detected as ar).
    rctx.extract(archive = deb_path, output = ar_dir)

    data_member = None
    for entry in rctx.path(ar_dir).readdir():
        if entry.basename.startswith("data.tar"):
            data_member = entry
            break

    if data_member == None:
        fail("No data archive found in {}".format(deb_path))

    # The archive type (tar.gz/tar.xz/tar.zst/...) is auto-detected from
    # the data_member's file extension.
    rctx.extract(archive = data_member, output = unpack_dir)

def _unpack(rctx, packages, dependency_set, sources, architecture):
    if architecture not in dependency_set["sets"]:
        fail("architecture '{}' is not present in dependency set '{}'".format(architecture, rctx.attr.depset_name))

    unpack_dir = "sysroot"
    work_dir = ".unpack_work_%s" % architecture

    package_keys = dependency_set_transitive_package_keys(packages, dependency_set, [architecture, "all"])
    for package_key in package_keys:
        package = packages[package_key]
        sanitized_key = util.sanitize(package_key)
        deb_path = "{}/{}.deb".format(work_dir, sanitized_key)
        ar_dir = "{}/{}.ar".format(work_dir, sanitized_key)

        rctx.download(
            output = deb_path,
            sha256 = package["sha256"],
            url = [
                uri + "/" + package["filename"]
                for uri in sources[package["suite"]]["uris"]
            ],
        )

        _materialize_deb_data_into_root(rctx, deb_path, ar_dir, unpack_dir)

    rctx.delete(work_dir)

def _sysroot_repository_impl(rctx):
    lockf = lockfile.from_json(rctx, rctx.attr.lock_content)

    sources = lockf.sources()
    packages = lockf.packages()
    dependency_sets = lockf.dependency_sets()
    dependency_set = dependency_sets[rctx.attr.depset_name]

    _unpack(
        rctx,
        packages,
        dependency_set,
        sources,
        rctx.attr.architecture,
    )

    rctx.file("sysroot/BUILD.bazel", _SYSROOT_BUILD_TMPL)

sysroot_repository = repository_rule(
    implementation = _sysroot_repository_impl,
    attrs = {
        "depset_name": attr.string(doc = "INTERNAL: DO NOT USE"),
        "lock_content": attr.string(doc = "INTERNAL: DO NOT USE"),
        "architecture": attr.string(doc = "INTERNAL: Architecture to unpack and expose as //sysroot:sysroot."),
    },
)
