"repository rule for generating a dependency graph from a lockfile."

load(":lockfile.bzl", "lockfile")
load(":starlark_codegen_utils.bzl", "starlark_codegen_utils")
load(":util.bzl", "util")

_ROOT_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

load("@rules_distroless//apt:defs.bzl", "dpkg_status")
load("@rules_distroless//distroless:defs.bzl", "flatten")
{tar_load}

exports_files(['packages.bzl'])

# Map Debian architectures to platform CPUs.
#
# For more info on Debian architectures, see:
#     * https://wiki.debian.org/SupportedArchitectures
#     * https://wiki.debian.org/ArchitectureSpecificsMemo
#     * https://www.debian.org/releases/stable/amd64/ch02s01.en.html#idm186
#
# For more info on Bazel's platforms CPUs see:
#     * https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD
_ARCHITECTURE_MAP = {{
    "amd64": "x86_64",
    "arm64": "arm64",
    "ppc64el": "ppc64le",
    "mips64el": "mips64",
    "s390x": "s390x",
    "i386": "x86_32",
    "armhf": "armv7e-mf",
    "all": "all",
}}

_ARCHITECTURES = {architectures}

[
   config_setting(
    name = os + "_" + arch,
    constraint_values = [
       "@platforms//os:" + os,
       "@platforms//cpu:" + _ARCHITECTURE_MAP[arch],
    ],
  )
  for os in ["linux"]
  for arch in _ARCHITECTURES
]


# List of installed packages. For now it's private.
_PACKAGES = {packages}

# Creates /var/lib/dpkg/status with installed package information.
dpkg_status(
    name = "dpkg_status",
    controls = select({{
        "//:linux_%s" % arch: ["//%s/%s:control" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)

filegroup(
    name = "packages",
    srcs = select({{
        "//:linux_%s" % arch: ["//%s/%s" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)


# A filegroup that contains all the packages and the dpkg status file.
filegroup(
    name = "{target_name}",
    srcs = [
        ":dpkg_status",
        ":packages",
    ],
    visibility = ["//visibility:public"],
)

{mergedusr_compat}

flatten(
    name = "flat",
    tars = [
        "{target_name}",
        {flat_extra_tars}
    ],
    deduplicate = True,
    visibility = ["//visibility:public"],
)
"""

_MERGEDUSR_COMPAT_TMPL = """\
tar(
    name = "mergedusr_compat",
    mtree = [
        "./bin type=link link=usr/bin",
        "./sbin type=link link=usr/sbin",
        "./lib type=link link=usr/lib",
        "./lib32 type=link link=usr/lib32",
        "./lib64 type=link link=usr/lib64",
        "./libx32 type=link link=usr/libx32",
    ],
    visibility = ["//visibility:public"],
)
"""

_UNPACK_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

filegroup(
    name = "{target_name}",
    srcs = ["."],
    visibility = ["//visibility:public"],
)
"""

_PACKAGE_TEMPLATE = '''\
"""Generated by rules_distroless. DO NOT EDIT."""

NO_MATCH_ERROR="""
Package "{target_name}" is not available for the current target platform.

Available Platforms: {available_platforms}

- Set `--platforms` on the command line.
- Perform a transition to one of the available platforms
"""

alias(
    name = "data",
    actual = select({data_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = select({control_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{target_name}",
    srcs = select({deps}, no_match_error = NO_MATCH_ERROR) + [":data"],
    visibility = ["//visibility:public"],
)

{extra}
'''

_DEB_CC_IMPORT = """
alias(
    name = "{target_name}",
    actual =  select({selects}),
    visibility = ["//visibility:public"],
)
"""

def dependency_set_package_selects(packages, dependency_set):
    """Build select() map of platform -> package labels for hub repo package filegroup."""
    selects = {}
    for arch, entries in dependency_set["sets"].items():
        names = {}
        for (short_key, version) in entries.items():
            package_key = short_key + "=" + version
            if package_key not in packages:
                fail("illegal state: package %s is not in lockfile" % package_key)
            names[packages[package_key]["name"]] = True

        selects[arch] = sorted(names.keys())

    return selects

def _dependency_set_package_keys(packages, dependency_set, architectures):
    keys = {}
    pending = []

    for architecture in architectures:
        entries = dependency_set["sets"].get(architecture, {})
        for (short_key, version) in entries.items():
            pending.append(short_key + "=" + version)

    for _ in range(len(packages)):
        if not pending:
            break

        current = pending
        pending = []
        for package_key in current:
            if package_key in keys:
                continue
            if package_key not in packages:
                fail("illegal state: package %s is not in lockfile" % package_key)

            keys[package_key] = True
            pending.extend(packages[package_key]["depends_on"])

    if pending:
        fail("dependency traversal for unpack package keys did not converge")

    return sorted(keys.keys())

def _ensure_mergedusr_compat_symlinks(rctx, unpack_dir):
    compat_symlinks = {
        "bin": "usr/bin",
        "sbin": "usr/sbin",
        "lib": "usr/lib",
        "lib32": "usr/lib32",
        "lib64": "usr/lib64",
        "libx32": "usr/libx32",
    }

    for root, target in compat_symlinks.items():
        root_path = unpack_dir + "/" + root
        target_path = unpack_dir + "/" + target

        if rctx.path(root_path).exists:
            continue
        if not rctx.path(target_path).exists:
            continue

        rctx.symlink(target_path, root_path)

def _materialize_deb_data_into_root(rctx, deb_path, work_dir, unpack_dir, bsdtar = None):
    # Part 1: unpack the data member from the .deb archive.
    # Uses .format() for Starlark-level substitutions only; the bash code here
    # contains no { } function braces so no doubling is necessary.
    setup_sh = """set -o errexit -o nounset -o pipefail
pkg='{pkg}'
work='{work}'
root='{root}'

member=""
while IFS= read -r entry; do
    case "$entry" in
        data.tar|data.tar.*)
            member="$entry"
            break
        ;;
    esac
done < <(ar t "$pkg")

if [[ -z "$member" ]]; then
    echo "No data archive found in $pkg" >&2
    exit 1
fi

data_archive="$work/$member"
ar p "$pkg" "$member" > "$data_archive"
""".format(
        pkg = deb_path,
        work = work_dir,
        root = str(rctx.path(unpack_dir)),
    )

    # Part 2: extract into the root, optionally normalising merged-/usr paths.
    # String concatenation (not .format()) is used here to avoid conflicts with
    # the bash function braces {{ }} produced by util.mergedusr_rewrite_script.
    if bsdtar != None:
        # Run the shared bsdtar rewrite script (same logic as deb_postfix) to
        # produce a normalised .tar.gz, then extract that into the root.
        extract_sh = (
            'data_file="$data_archive"\n' +
            'layer="$work/content.tar.gz"\n\n' +
            util.mergedusr_rewrite_script(str(bsdtar), dollar = "$") + "\n\n" +
            "tar --extract --file \"$layer\" --directory \"$root\" --no-same-owner --no-same-permissions\n" +
            'rm -f "$layer"\n'
        )
    else:
        extract_sh = "tar --extract --file \"$data_archive\" --directory \"$root\" --no-same-owner --no-same-permissions\n"

    extraction = rctx.execute([
        "bash",
        "-c",
        setup_sh + extract_sh,
    ])
    if extraction.return_code != 0:
        fail("Failed extracting deb payload from {}:\n{}\n{}".format(deb_path, extraction.stdout, extraction.stderr))

def _unpack(rctx, packages, dependency_set, sources, mergedusr):
    concrete_arches = [
        arch
        for arch in dependency_set["sets"].keys()
        if arch != "all"
    ]
    if not concrete_arches:
        fail("unpack requires at least one concrete target architecture")

    bsdtar = None
    if mergedusr:
        if not rctx.attr.bsdtar:
            fail(
                "bsdtar is required for mergedusr unpacking but was not provided. " +
                "This is an internal error; please file a bug.",
            )
        bsdtar = rctx.path(rctx.attr.bsdtar)

    for architecture in concrete_arches:
        unpack_dir = "unpack_%s" % architecture
        work_dir = str(rctx.path(".unpack_work_%s" % architecture))
        make_work_dir = rctx.execute(["mkdir", "-p", work_dir, str(rctx.path(unpack_dir))])
        if make_work_dir.return_code != 0:
            fail("Failed creating unpack work dir {}".format(work_dir))

        package_keys = _dependency_set_package_keys(packages, dependency_set, [architecture, "all"])
        for package_key in package_keys:
            package = packages[package_key]
            deb_path = "{}/{}.deb".format(work_dir, util.sanitize(package_key))

            rctx.download(
                output = deb_path,
                sha256 = package["sha256"],
                url = [
                    uri + "/" + package["filename"]
                    for uri in sources[package["suite"]]["uris"]
                ],
            )

            _materialize_deb_data_into_root(rctx, deb_path, work_dir, unpack_dir, bsdtar = bsdtar)

        if mergedusr:
            _ensure_mergedusr_compat_symlinks(rctx, unpack_dir)

        cleanup = rctx.execute(["rm", "-rf", work_dir])
        if cleanup.return_code != 0:
            fail("Failed cleaning unpack work dir {}".format(work_dir))

        rctx.file(
            unpack_dir + "/BUILD.bazel",
            _UNPACK_BUILD_TMPL.format(target_name = unpack_dir),
        )

def _translate_dependency_set_impl(rctx):
    package_template = rctx.read(rctx.attr.package_template)
    lockf = lockfile.from_json(rctx, rctx.attr.lock_content)

    sources = lockf.sources()
    packages = lockf.packages()
    dependency_sets = lockf.dependency_sets()
    dependency_set = dependency_sets[rctx.attr.depset_name]

    package_selects = dependency_set_package_selects(packages, dependency_set)

    packages_to_architectures = {}

    for architecture in dependency_set["sets"].keys():
        for (short_key, version) in dependency_set["sets"][architecture].items():
            package_key = short_key + "=" + version
            repo_name = util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr)
            package = packages[package_key]

            packages_to_architectures.setdefault(
                package["name"],
                struct(
                    name = package["name"],
                    architectures = {},
                ),
            ).architectures[architecture] = package_key

            rctx.file(
                "%s/%s/BUILD.bazel" % (package["name"], architecture),
                package_template.format(
                    target_name = architecture,
                    data_targets = '"@%s//:data"' % repo_name,
                    control_targets = '"@%s//:control"' % repo_name,
                    src = '"@%s//:data"' % repo_name,
                    deps = [
                        "@" + util.package_repo_name(dep_key, mergedusr = rctx.attr.mergedusr) + "//:data"
                        for dep_key in package["depends_on"]
                        if packages[dep_key]["architecture"] in [architecture, "all"]
                    ],
                    urls = [
                        uri + "/" + package["filename"]
                        for uri in sources[package["suite"]]["uris"]
                    ],
                    name = package["name"],
                    arch = package["architecture"],
                    sha256 = package["sha256"],
                    repo_name = repo_name,
                ),
            )

    for (_, info) in packages_to_architectures.items():
        package_name = info.name

        architectures = info.architectures.keys()

        extra = ""
        if package_name.endswith("-dev"):
            target_name = package_name.removesuffix("-dev")
            extra = _DEB_CC_IMPORT.format(
                target_name = target_name,
                selects = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "@%s//:%s" % (util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr), target_name)
                    for (architecture, package_key) in info.architectures.items()
                }),
            )

        rctx.file(
            "%s/BUILD.bazel" % package_name,
            _PACKAGE_TEMPLATE.format(
                target_name = package_name,
                data_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:data" % (package_name, architecture)
                    for architecture in architectures
                }),
                control_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:control" % (package_name, architecture)
                    for architecture in architectures
                }),
                deps = starlark_codegen_utils.to_dict_list_attr({
                    "//:linux_%s" % architecture: ["//%s/%s" % (package_name, architecture)]
                    for architecture in architectures
                }),
                extra = extra,
                available_platforms = " ".join([
                    "linux/" + arch
                    for arch in architectures
                ]),
            ),
        )

    if rctx.attr.unpack:
        _unpack(
            rctx,
            packages,
            dependency_set,
            sources,
            rctx.attr.mergedusr,
        )

    rctx.file("BUILD.bazel", _ROOT_BUILD_TMPL.format(
        target_name = util.get_repo_name(rctx.attr.name),
        packages = starlark_codegen_utils.to_dict_list_attr(package_selects),
        architectures = starlark_codegen_utils.to_list_attr(dependency_set["sets"].keys()),
        tar_load = 'load("@tar.bzl", "tar")' if rctx.attr.mergedusr else "",
        mergedusr_compat = _MERGEDUSR_COMPAT_TMPL if rctx.attr.mergedusr else "",
        flat_extra_tars = '":mergedusr_compat",' if rctx.attr.mergedusr else "",
    ))

translate_dependency_set = repository_rule(
    implementation = _translate_dependency_set_impl,
    attrs = {
        "depset_name": attr.string(doc = "INTERNAL: DO NOT USE"),
        "lock_content": attr.string(doc = "INTERNAL: DO NOT USE"),
        "unpack": attr.bool(default = False, doc = "INTERNAL: Whether to expose repository-time unpacked archives via //unpack_<debian_arch>."),
        "mergedusr": attr.bool(default = False, doc = "INTERNAL: Whether package layers were normalized with merged-/usr semantics."),
        "bsdtar": attr.label(default = None, allow_single_file = True, doc = "INTERNAL: bsdtar binary from bsd_tar_toolchains, required when mergedusr=True and unpack=True."),
        "package_template": attr.label(default = "//apt/private:package.BUILD.tmpl"),
    },
)
