"repository rule for generating a dependency graph from a lockfile."

load(":lockfile.bzl", "lockfile")
load(":starlark_codegen_utils.bzl", "starlark_codegen_utils")
load(":util.bzl", "util")
load(":version.bzl", version_lib = "version")

_ROOT_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

load("@rules_distroless//apt:defs.bzl", "dpkg_status")
load("@rules_distroless//distroless:defs.bzl", "flatten")

exports_files(['packages.bzl'])

# Map Debian architectures to platform CPUs.
#
# For more info on Debian architectures, see:
#     * https://wiki.debian.org/SupportedArchitectures
#     * https://wiki.debian.org/ArchitectureSpecificsMemo
#     * https://www.debian.org/releases/stable/amd64/ch02s01.en.html#idm186
#
# For more info on Bazel's platforms CPUs see:
#     * https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD
_ARCHITECTURE_MAP = {{
    "amd64": "x86_64",
    "arm64": "arm64",
    "ppc64el": "ppc64le",
    "mips64el": "mips64",
    "s390x": "s390x",
    "i386": "x86_32",
    "armhf": "armv7e-mf",
    "all": "all",
}}

_ARCHITECTURES = {architectures}

[
   config_setting(
    name = os + "_" + arch,
    constraint_values = [
       "@platforms//os:" + os,
       "@platforms//cpu:" + _ARCHITECTURE_MAP[arch],
    ],
    visibility = ["//:__subpackages__"],
  )
  for os in ["linux"]
  for arch in _ARCHITECTURES
]


# List of installed packages. For now it's private.
_PACKAGES = {packages}

# Creates /var/lib/dpkg/status with installed package information.
dpkg_status(
    name = "dpkg_status",
    controls = select({{
        "//:linux_%s" % arch: ["//%s/%s:control" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)

filegroup(
    name = "packages",
    srcs = select({{
        "//:linux_%s" % arch: ["//%s/%s" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)


# A filegroup that contains all the packages and the dpkg status file.
filegroup(
    name = "{target_name}",
    srcs = [
        ":dpkg_status",
        ":packages",
    ],
    visibility = ["//visibility:public"],
)

flatten(
    name = "flat",
    tars = [
        "{target_name}",
    ],
    deduplicate = True,
    visibility = ["//visibility:public"],
)
"""

_PACKAGE_TEMPLATE = '''\
"""Generated by rules_distroless. DO NOT EDIT."""

NO_MATCH_ERROR="""
Package "{target_name}" is not available for the current target platform.

Available Platforms: {available_platforms}

- Set `--platforms` on the command line.
- Perform a transition to one of the available platforms
"""

alias(
    name = "data",
    actual = select({data_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = select({control_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{target_name}",
    srcs = select({deps}, no_match_error = NO_MATCH_ERROR) + [":data"],
    visibility = ["//visibility:public"],
)

{extra}
'''

_DEB_CC_IMPORT = """
alias(
    name = "{target_name}",
    actual =  select({selects}),
    visibility = ["//visibility:public"],
)
"""

# Builds the fully-qualified package key (`<short_key>=<version>`) used to
# index into the lockfile's `packages` map from a dependency_set's per-
# architecture `{short_key: version}` entries.
def _package_key(short_key, version):
    return short_key + "=" + version

# Returns the `depends_on` keys of `package` whose architecture is present in
# `allowed_architectures` (a set-like dict of architecture -> True).
#
# Avoids mixing architectures: a dependency is only included if it was built
# for an allowed architecture, or is architecture-independent ("all"). Without
# this scoping, a package's `depends_on` (which spans every architecture the
# lockfile knows about) would leak foreign-architecture deps into a single
# architecture's target/closure, causing file duplication that confuses
# `flatten`.
def _package_dep_keys_for_architectures(packages, package, allowed_architectures):
    return [
        dep_key
        for dep_key in package["depends_on"]
        if packages[dep_key]["architecture"] in allowed_architectures
    ]

# Computes the `@repo//:data` labels a package's per-architecture BUILD.bazel
# should depend on for the given architecture.
def _package_deps_for_architecture(packages, package, architecture, mergedusr = False):
    allowed_architectures = {architecture: True, "all": True}
    return [
        "@" + util.package_repo_name(dep_key, mergedusr = mergedusr) + "//:data"
        for dep_key in _package_dep_keys_for_architectures(packages, package, allowed_architectures)
    ]

# Validates a dependency_set against the lockfile's `packages` map.
def verify_dependency_set(packages, dependency_set):
    package_coords_to_versions = {}

    for (architecture, entries) in dependency_set["sets"].items():
        for (short_key, version) in entries.items():
            package_key = _package_key(short_key, version)
            if package_key not in packages:
                    fail("illegal state: package %s is not in lockfile" % package_key)

            package_name = packages[package_key]["name"]
            package_coords = (package_name, architecture)
            recorded_version = package_coords_to_versions.setdefault(package_coords, version)
            if recorded_version != version:
                fail("""Two different source versions detected for package `{name}:{arch}` : {v1} and {v2}.
This usually means that a distribution ships different versions of this dependency for different architectures.

Please unify the versions manually, or use separate `apt.install` calls (with distinct `dependency_set` names) for each version of the dependency.
""".format(name = package_name, arch = architecture, v1 = recorded_version, v2 = version))

def dependency_set_transitive_package_keys(packages, dependency_set, architectures):
    keys = {}
    pending = []
    allowed_architectures = {
        architecture: True
        for architecture in architectures
    }

    verify_dependency_set(packages, dependency_set)

    for architecture in architectures:
        entries = dependency_set["sets"].get(architecture, {})
        for (short_key, version) in entries.items():
            pending.append(_package_key(short_key, version))

    for _ in range(len(packages)):
        if not pending:
            break

        current = pending
        pending = []
        for package_key in current:
            if package_key in keys:
                continue

            keys[package_key] = True

            # Keep closure architecture-scoped even when traversing from
            # architecture = all packages with mixed-arch dependency metadata.
            pending.extend(_package_dep_keys_for_architectures(packages, packages[package_key], allowed_architectures))

    if pending:
        fail("dependency traversal for package keys did not converge")

    return sorted(keys.keys())

def _translate_dependency_set_impl(rctx):
    package_template = rctx.read(rctx.attr.package_template)
    lockf = lockfile.from_json(rctx, rctx.attr.lock_content)

    sources = lockf.sources()
    packages = lockf.packages()
    dependency_sets = lockf.dependency_sets()
    dependency_set = dependency_sets[rctx.attr.depset_name]

    packages_to_architectures = {}

    # Maps each architecture to the list of package names installed for it.
    # Used to populate the root repo's _PACKAGES table.
    architectures_to_package_names = {}

    verify_dependency_set(packages, dependency_set)

    for architecture in dependency_set["sets"].keys():
        architectures_to_package_names[architecture] = []

        for (short_key, version) in dependency_set["sets"][architecture].items():
            package_key = _package_key(short_key, version)
            repo_name = util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr)
            package = packages[package_key]
            package_name = package["name"]

            architectures_to_package_names[architecture].append(package_name)

            # Keyed by package name (not name+version): a package rebuilt with a
            # different binNMU per architecture is a single target whose data,
            # control and deps are selected per architecture.
            packages_to_architectures.setdefault(
                package_name,
                struct(
                    name = package_name,
                    architectures = {},
                ),
            ).architectures[architecture] = package_key

            rctx.file(
                "%s/%s/BUILD.bazel" % (package["name"], architecture),
                package_template.format(
                    target_name = architecture,
                    data_targets = '"@%s//:data"' % repo_name,
                    control_targets = '"@%s//:control"' % repo_name,
                    src = '"@%s//:data"' % repo_name,
                    deps = _package_deps_for_architecture(packages, package, architecture, mergedusr = rctx.attr.mergedusr),
                    urls = [
                        uri + "/" + package["filename"]
                        for uri in sources[package["suite"]]["uris"]
                    ],
                    name = package["name"],
                    arch = package["architecture"],
                    sha256 = package["sha256"],
                    repo_name = repo_name,
                ),
            )

    for (_, info) in packages_to_architectures.items():
        package_name = info.name

        architectures = info.architectures.keys()

        extra = ""
        if package_name.endswith("-dev"):
            target_name = package_name.removesuffix("-dev")
            extra = _DEB_CC_IMPORT.format(
                target_name = target_name,
                selects = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "@%s//:%s" % (util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr), target_name)
                    for (architecture, package_key) in info.architectures.items()
                }),
            )

        rctx.file(
            "%s/BUILD.bazel" % package_name,
            _PACKAGE_TEMPLATE.format(
                target_name = package_name,
                data_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:data" % (package_name, architecture)
                    for architecture in architectures
                }),
                control_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:control" % (package_name, architecture)
                    for architecture in architectures
                }),
                deps = starlark_codegen_utils.to_dict_list_attr({
                    "//:linux_%s" % architecture: ["//%s/%s" % (package_name, architecture)]
                    for architecture in architectures
                }),
                extra = extra,
                available_platforms = " ".join([
                    "linux/" + arch
                    for arch in architectures
                ]),
            ),
        )

    rctx.file("BUILD.bazel", _ROOT_BUILD_TMPL.format(
        target_name = util.get_repo_name(rctx.attr.name),
        packages = starlark_codegen_utils.to_dict_list_attr(architectures_to_package_names),
        architectures = starlark_codegen_utils.to_list_attr(dependency_set["sets"].keys()),
    ))

translate_dependency_set = repository_rule(
    implementation = _translate_dependency_set_impl,
    attrs = {
        "depset_name": attr.string(doc = "INTERNAL: DO NOT USE"),
        "lock_content": attr.string(doc = "INTERNAL: DO NOT USE"),
        "mergedusr": attr.bool(default = False, doc = "INTERNAL: Whether package layers were normalized with merged-/usr semantics."),
        "package_template": attr.label(default = "//apt/private:package.BUILD.tmpl"),
    },
)
